package pe.com.sedapal.agi.model.enums;

import java.io.Serializable;

public enum CorreoConstante implements Serializable {
    
	CONSTANTE_PARAMETRO_CORREO("Listado de Parametros de Correo"),
	CONSTANTE_CORREO_REMITENTE("Correo Remitente"),
	CONSTANTE_USUARIO_REMITENTE("Usuario Remitente"),
	CONSTANTE_PASSWORD_REMITENTE("Password Remitente"),
	CONSTANTE_RUTA_IMAGEN("Ruta de Imagen de Correo"),
	CONSTANTE_IMAGEN_FIRMA("Firma de Correo"),
	CONSTANTE_IMAGEN_PIE("Pie de Pagina de Correo"),
	
	IMAGEN_SEDAPAL("IMAGEN SEDAPAL"),
	IMAGEN_NO_RESPONDER("IMAGEN NO RESPONDER"),
	
	NOTI_REGI_SOLI("ENVIO DE NOTIFICACION DE REGISTRO DE SOLICITUD DE REVISION"),
	NOTI_APRO_SOLI("NOTIFICAR LA APROBACION DE SOLICITUD DE REVISION DE DOCUMENTO"),
	NOTI_PLAZ_ATEN("NOTIFICACION DE PLAZO DE ATENCION"),
	NOTI_DOCU_LIBE("NOTIFICACION DE DOCUMENTO LIBERADO"),
	NOTI_COPI_REGI("ENVIO DE NOTIFICACION DE SOLICITUD DE COPIA IMPRESA"),
	NOTI_COPI_RECH("NOTIFICACION DE RECHAZO DE COPIA IMPRESA"),
	NOTI_COPI_IMPR("NOTIFICACION POR IMPRESION DE DOCUMENTO"),
	NOTI_CANC_SOLI("ENVIO DE NOTIFICACION DE REGISTRO DE SOLICITUD DE CANCELACION DE DOCUMENTO"),
	NOTI_CANC_APRO("ENVIO DE NOTIFICACION DE APROBACION DE LA SOLICITUD DE CANCELACION DEL DOCUMENTO"),
	NOTI_CANC_EJEC("ENVIO DE NOTIFICACION DE LA EJECUCCION DE LA CANCELACION DEL DOCUMENTO"),
	NOTI_CANC_RECH("ENVIO DE NOTIFICACION DE RECHAZO DE LA CANCELACION DEL DOCUMENTO"),
	NOTI_RECH_DOCU("NOTIFICACION DE RECHAZO DE DOCUMENTO"),
	NOTI_PROG_SOLI("ENVIO DE NOTIFICACION DE PROGRAMACION DEL PROCESO DE REVISION Y ACTUALIZACION DE DOCUMENTOS"),
	NOTI_PROG_DIST("ENVIO DE NOTIFICACION DE LA DISTRIBUCION DEL PROCESO DE REVISION Y ACTUALIZACION DE DOCUMENTOS"),
	NOTI_PROG_EJEC("ENVIO DE NOTIFICACION DE LA EJECUCION DEL PROCESO DE REVISION Y ACTUALIZACION DE DOCUMENTOS"),
	NOTI_APRO("NOTIFICAR LA APROBACION DE REVISION"),
	NOTI_SEDA("CORREO_SEDAPAL"),	
	NOTI_CAMB_PART("NOTIFICAR CAMBIO DEL EQUIPO PARTICIPANTE"),
	NOTI_ALER_ANTE_PLAZ("NOTIFICACION DE ALERTA DE PLAZO DE SOLICITUD DE REVISION ANTES DEL PLAZO"),
	NOTI_ALER_DESP_PLAZ("NOTIFICACION DE ALERTA DE PLAZO DE SOLICITUD DE REVISION DESPUES DEL PLAZO");

    private final String text;

    CorreoConstante(final String text) {
        this.text = text;
    }
    @Override
    public String toString() {
        return text;
    }
	
}